export default {
  USER: "/user/",
  LOGIN: "/user/login",
  REGISTER: "/user/signup",
  FORGET_PASSWORD: "/user/forgetPassword",
  CONFIRM_PASSWORD: "/user/confirmPassword",
  CHANGE_PASSWORD: "/user/changePassword",
  FOLLOW: "/user/follow",
  UNFOLLOW: "/user/unfollow",
  MY_PROFILE: "/user/myProfile",
  NOTIFICATIONS_COUNT: "/user/notifications-count",
  NOTIFICATIONS: "/user/notifications",
  USER_INFO: "/user/userInfo",
  GET_TOKENS: "/user/get-tokens",
  REGISTER_DEVICE_TOKEN: "/user/register-device-token",
  DEVICE_SETTINGS: "/user/device-settings",
  BLOCK: "/user/block",
  FOLLOWERS: "/user/follower",
  FOLLOWING: "/user/following",
  LOCATION: "/user/location",
  LOCATION_SETTINGS: "/user/location-settings",
  AROUND_ME: "/user/around-me",
  REFERRAL: "/user/referral",
  REFERRAL_CODE: "/user/referrals-count",
  SUD: "/user/list",
  ACCEPT_CHAT_TERMS: "/user/accept-chat-terms",
  getUsers: "user/list?source=app",
  userLocation: "user/location",
  locationSettings: "user/location-settings",
  usersAroundMe: "user/around-me",
  REVIEWS: (uuid: string): string => `/feeds/${uuid}/reviews`,
  UPLOAD: "/upload/"
};
